#!/bin/sh

# dependencies: waybar, kanshi, fuzzel, river-bedload, slurp, grim, wf-recorder/wl-screenrec, wl-clipboard, waylock/swaylock, wlopm, xdg-desktop-portals-wlr
# fnott, lswt, wbg

# Check if we're running systemd or openrc
init=$(ps --no-headers -o comm 1)

riverctl map normal Super+Shift q exit
# riverctl map normal Super Return spawn 'wezterm && sleep 1 && riverctl focus-view next && riverctl focus-view previous'
riverctl map normal Super Return spawn kitty
riverctl map normal Super Escape spawn "fuzzel"
riverctl map normal Super q close
riverctl map normal Super d close
riverctl map normal Super m focus-output next
riverctl map normal Super+Shift m spawn "riverctl send-to-output next && riverctl focus-output next"
riverctl map normal Super j focus-view next
riverctl map normal Super k focus-view previous
riverctl map normal Super h focus-output previous
riverctl map normal Super l focus-output next
riverctl map normal Super+Shift j swap next
riverctl map normal Super+Shift k swap previous
riverctl map normal Super+Shift h send-to-output -current-tags previous
riverctl map normal Super+Shift l send-to-output -current-tags next
riverctl map normal Super i send-layout-cmd rivertile "main-count +1"
riverctl map normal Super o send-layout-cmd rivertile "main-count -1"
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"
riverctl map normal Super Comma toggle-float
riverctl map normal Super f toggle-fullscreen
riverctl map normal Super p spawn 'delegator -g'

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

wallpaper=$(find -L /home/vital/Pictures/wallpaper/ -type f | sort -R | head -1)

mode_exit="exit: loc[k], [l]ogout, s[u]spend, [r]eboot, [s]hutdown"
riverctl declare-mode "$mode_exit"
riverctl map normal Super x enter-mode "$mode_exit"
riverctl map "$mode_exit" None k spawn "riverctl enter-mode normal && swaylock -f -i $wallpaper"
riverctl map "$mode_exit" None l exit
riverctl map "$mode_exit" None u spawn 'loginctl suspend'
if [ "$init" = "systemd" ]
then
    riverctl map "$mode_exit" None r spawn 'systemctl reboot'
    riverctl map "$mode_exit" None s spawn 'shutdown -h now'
else
    riverctl map "$mode_exit" None r spawn 'loginctl reboot'
    riverctl map "$mode_exit" None s spawn 'loginctl poweroff'
fi
riverctl map "$mode_exit" None Escape enter-mode normal
riverctl map "$mode_exit" None Return enter-mode normal

# Screen capture
screenshot="a: selected, s: current screen, d: selected clipboard, f: current screen clipboard, g: VS Code"
riverctl declare-mode "$screenshot"
riverctl map normal None Print enter-mode "$screenshot"
riverctl map "$screenshot" None a spawn 'grim -g "$(slurp)" ~/Pictures/Screenshots/ps_$(date +"%Y%m%d%H%M%S").png && riverctl enter-mode normal'
riverctl map "$screenshot" None s spawn 'grim -o "$(/home/vital/.local/bin/river-bedload -print outputs | jq -r ".[] | select(.focused) | .name")" ~/Pictures/Screenshots/ps_$(date +"%Y%m%d%H%M%S").png && riverctl enter-mode normal'
riverctl map "$screenshot" None d spawn 'grim -g "$(slurp)" - | wl-copy && riverctl enter-mode normal'
riverctl map "$screenshot" None f spawn 'grim -o "$(/home/vital/.local/bin/river-bedload -print outputs | jq -r ".[] | select(.focused) | .name")" - | wl-copy && riverctl enter-mode normal'
# riverctl map "$screenshot" None g spawn 'grim -g "$(slurp)" - | swappy -f - && riverctl enter-mode normal'
riverctl map "$screenshot" None g spawn 'grim -g "1524,470 2471x1286" ~/Pictures/Screenshots/ps_$(date +"%Y%m%d%H%M%S").png && riverctl enter-mode normal'
riverctl map "$screenshot" None Escape enter-mode normal
riverctl map "$screenshot" None Return enter-mode normal
riverctl map "$screenshot" None Print enter-mode normal

# Screen recording
riverctl map normal Shift Print spawn "/home/vital/.local/bin/toggle-screen-recorder.sh"

riverctl border-width 3
riverctl border-color-focused 0x93B259
# riverctl border-color-focused 0xE66868
riverctl border-color-unfocused 0x708089
riverctl border-color-urgent 0xE66868
# riverctl border-color-urgent 0x93B259
# riverctl keyboard-layout -options compose:caps us
riverctl input pointer-13652-62758-compx_2.4G_Dual_Mode_Mouse accel-profile flat

# riverctl xcursor-theme Oxygen_White

riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 -main-ratio 0.7 &

# Use lswt to find app-ids and titles for rules
riverctl rule-add ssd
riverctl rule-add -app-id Eclipse tags 2
# riverctl rule-add -app-id Eclipse output DP-1

# riverctl spawn 'dbus-run-session pipewire'
riverctl spawn "gentoo-pipewire-launcher restart"
riverctl spawn 'swayidle timeout 600 "swaylock -i '"$wallpaper"'" timeout 600 "wlopm --off \*" resume "wlopm --on \*"'
# -s flag was introduced in 1.3.0, which is not in gentoo guru repo yet
riverctl spawn "wbg -s $wallpaper || wbg $wallpaper"
riverctl spawn "waybar"
riverctl spawn "kanshi"

# https://wiki.archlinux.org/title/XDG_Desktop_Portal#Portal_does_not_start
if [ "$init" = "systemd" ]
then
    riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_CONFIG_HOME"
    riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river:wlroots XDG_CONFIG_HOME"
else
    riverctl spawn "exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river XDG_CONFIG_HOME"
fi

riverctl spawn '~/.config/river/local.sh'
