#!/bin/bash

[[ ! -d /sys/class/backlight ]] && exit

BRIGHTNESS=$(echo "scale=0; $(cat /sys/class/backlight/*/brightness) * 100 / $(cat /sys/class/backlight/*/max_brightness)" | bc -l )
echo "${BRIGHTNESS}%"
