#!/bin/bash

statusline=$(amixer get Master | tail -n 1)
status=$(echo "${statusline}" | grep -wo "on")
volume=$(echo "${statusline}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
    echo "${volume}%"
else
    echo "MUTE"
fi
