#!/bin/bash

if [[ -n "$card" ]]; then
    card="-c "$card
else
    card=""
fi

statusline=$(amixer $card get Master | tail -n 1)
status=$(echo "${statusline}" | grep -wo "on")
volume=$(echo "${statusline}" | awk -F "[][]" '{ print $2 }')

if [[ "${status}" == "on" ]]; then
    echo "${volume}"
else
    echo "MUTE"
fi
