[which]
mask            = { bg = "#e7d2be" }

[mode]
normal_main = { fg = "white", bg = "blue", bold = true }
select_main = { fg = "white", bg = "red", bold = true }
unset_main = { fg = "white", bg = "red", bold = true }
