[which]
mask            = { bg = "#e7d2be" }

[mode]
normal_main = { fg = "white", bg = "blue", bold = true }
select_main = { fg = "white", bg = "red", bold = true }
unset_main = { fg = "white", bg = "red", bold = true }

[icon]
dirs = [
  { name = "documents", text = "󱧶", fg = "blue" },
  { name = "downloads", text = "󰉍", fg = "blue" },
  { name = "music", text = "󱍙", fg = "blue" },
  { name = "pictures", text = "󰉏", fg = "blue" },
  { name = "videos", text = "󱧺", fg = "blue" },
  { name = "media", text = "󰉒", fg = "blue" },
  { name = "mnt", text = "󰉒", fg = "blue" },
  { name = "home", text = "󱂵", fg = "blue" },
  { name = "etc", text = "󱁿", fg = "blue" },
  { name = ".config", text = "󱂀", fg = "blue" },
]

files = [
  { name = ".bash_profile", text = "󱁼", fg = "black" },
  { name = ".bashrc", text = "󱁼", fg = "black" },
  { name = ".zprofile", text = "󱁼", fg = "black" },
  { name = ".zshenv", text = "󱁼", fg = "black" },
  { name = ".zshrc", text = "󱁼", fg = "black" },
  { name = ".vimrc", text = "󱁼", fg = "black" },
  { name = "vimrc", text = "󱁻", fg = "black" },
  { name = "config", text = "󱁻", fg = "black" },
]

exts = [
  # archives
  { name = "7z", text = "󰛫" },
  { name = "bz", text = "󰛫" },
  { name = "bz2", text = "󰛫" },
  { name = "bz3", text = "󰛫" },
  { name = "gz", text = "󰛫" },
  { name = "rar", text = "󰛫" },
  { name = "tar", text = "󰛫" },
  { name = "tgz", text = "󰛫" },
  { name = "txz", text = "󰛫" },
  { name = "xz", text = "󰛫" },
  { name = "zip", text = "󰛫" },
  { name = "zst", text = "󰛫" },

  # documents
  { name = "md", text = "󰈙", fg = "black" },
  { name = "txt", text = "󰈙" , fg = "black"  },
  { name = "org", text = "󰈙" , fg = "black"  },

  # music, images, videos
  { name = "3gp", text = "󰈫" },
  { name = "aac", text = "󰈣" },
  { name = "aif", text = "󰈣" },
  { name = "aiff", text = "󰈣" },
  { name = "ape", text = "󰈣" },
  { name = "avif", text = "󰈟" },
  { name = "bmp", text = "󰈟" },
  { name = "cast", text = "󰈫" },
  { name = "flac", text = "󰈣" },
  { name = "gif", text = "󰈟" },
  { name = "ico", text = "󰈟" },
  { name = "jpeg", text = "󰈟" },
  { name = "jpg", text = "󰈟" },
  { name = "jxl", text = "󰈟" },
  { name = "m4a", text = "󰈣" },
  { name = "m4v", text = "󰈫" },
  { name = "mkv", text = "󰈫" },
  { name = "mov", text = "󰈫" },
  { name = "mp3", text = "󰈣" },
  { name = "mp4", text = "󰈫" },
  { name = "oga", text = "󰈣" },
  { name = "ogg", text = "󰈣" },
  { name = "ogv", text = "󰈫" },
  { name = "ogx", text = "󰈫" },
  { name = "opus", text = "󰈣" },
  { name = "pcm", text = "󰈣" },
  { name = "png", text = "󰈟" },
  { name = "spx", text = "󰈣" },
  { name = "wav", text = "󰈣" },
  { name = "webm", text = "󰈫" },
  { name = "webp", text = "󰈟" },
  { name = "wma", text = "󰈣" },
  { name = "wmv", text = "󰈫" },
  { name = "wv", text = "󰈣" },
  { name = "wvc", text = "󰈣" },

  # config files
  { name = "cfg", text = "󱁻", fg = "black" },
  { name = "conf", text = "󱁻", fg = "black" },
  { name = "ini", text = "󱁻", fg = "black" },
  { name = "yaml", text = "󱁻", fg = "black" },
  { name = "yml", text = "󱁻", fg = "black" },

  # code
  { name = "ada", text = "󰈮" },
  { name = "adb", text = "󰈮" },
  { name = "ads", text = "󰈮" },
  { name = "apl", text = "󰈮" },
  { name = "applescript", text = "󰈮" },
  { name = "asc", text = "󰈮" },
  { name = "asm", text = "󰈮" },
  { name = "awk", text = "󰈮" },
  { name = "bash", text = "󰈮" },
  { name = "bat", text = "󰈮" },
  { name = "bzl", text = "󰈮" },
  { name = "c", text = "󰈮" },
  { name = "c++", text = "󰈮" },
  { name = "cbl", text = "󰈮" },
  { name = "cc", text = "󰈮" },
  { name = "cfc", text = "󰈮" },
  { name = "cfm", text = "󰈮" },
  { name = "clj", text = "󰈮" },
  { name = "cljc", text = "󰈮" },
  { name = "cljs", text = "󰈮" },
  { name = "cmake", text = "󰈮" },
  { name = "cob", text = "󰈮" },
  { name = "cobol", text = "󰈮" },
  { name = "coffee", text = "󰈮" },
  { name = "cp", text = "󰈮" },
  { name = "cpp", text = "󰈮" },
  { name = "cpy", text = "󰈮" },
  { name = "cr", text = "󰈮" },
  { name = "cs", text = "󰈮" },
  { name = "csh", text = "󰈮" },
  { name = "cshtml", text = "󰈮" },
  { name = "cson", text = "󰈮" },
  { name = "cu", text = "󰈮" },
  { name = "cuh", text = "󰈮" },
  { name = "cxx", text = "󰈮" },
  { name = "d", text = "󰈮" },
  { name = "dart", text = "󰈮" },
  { name = "ebuild", text = "󰈮" },
  { name = "el", text = "󰈮" },
  { name = "elm", text = "󰈮" },
  { name = "erl", text = "󰈮" },
  { name = "ex", text = "󰈮" },
  { name = "exs", text = "󰈮" },
  { name = "f90", text = "󰈮" },
  { name = "feature", text = "󰈮" },
  { name = "fish", text = "󰈮" },
  { name = "frag", text = "󰈮" },
  { name = "fs", text = "󰈮" },
  { name = "fsi", text = "󰈮" },
  { name = "fsx", text = "󰈮" },
  { name = "gd", text = "󰈮" },
  { name = "gemspec", text = "󰈮" },
  { name = "geom", text = "󰈮" },
  { name = "glsl", text = "󰈮" },
  { name = "go", text = "󰈮" },
  { name = "h", text = "󰈮" },
  { name = "hh", text = "󰈮" },
  { name = "hpp", text = "󰈮" },
  { name = "hrl", text = "󰈮" },
  { name = "hs", text = "󰈮" },
  { name = "hx", text = "󰈮" },
  { name = "hxx", text = "󰈮" },
  { name = "ino", text = "󰈮" },
  { name = "java", text = "󰈮" },
  { name = "jl", text = "󰈮" },
  { name = "js", text = "󰈮" },
  { name = "jsx", text = "󰈮" },
  { name = "kicad_pcb", text = "󰈮" },
  { name = "ksh", text = "󰈮" },
  { name = "kt", text = "󰈮" },
  { name = "kts", text = "󰈮" },
  { name = "lhs", text = "󰈮" },
  { name = "lua", text = "󰈮" },
  { name = "m", text = "󰈮" },
  { name = "mk", text = "󰈮" },
  { name = "ml", text = "󰈮" },
  { name = "mli", text = "󰈮" },
  { name = "mm", text = "󰈮" },
  { name = "mo", text = "󰈮" },
  { name = "nim", text = "󰈮" },
  { name = "nix", text = "󰈮" },
  { name = "nu", text = "󰈮" },
  { name = "pck", text = "󰈮" },
  { name = "php", text = "󰈮" },
  { name = "pl", text = "󰈮" },
  { name = "pls", text = "󰈮" },
  { name = "pm", text = "󰈮" },
  { name = "pp", text = "󰈮" },
  { name = "pro", text = "󰈮" },
  { name = "ps1", text = "󰈮" },
  { name = "psd1", text = "󰈮" },
  { name = "psm1", text = "󰈮" },
  { name = "pxd", text = "󰈮" },
  { name = "pxi", text = "󰈮" },
  { name = "py", text = "󰈮" },
  { name = "pyw", text = "󰈮" },
  { name = "pyx", text = "󰈮" },
  { name = "qml", text = "󰈮" },
  { name = "r", text = "󰈮" },
  { name = "rake", text = "󰈮" },
  { name = "rb", text = "󰈮" },
  { name = "rs", text = "󰈮" },
  { name = "s", text = "󰈮" },
  { name = "sbt", text = "󰈮" },
  { name = "sc", text = "󰈮" },
  { name = "scad", text = "󰈮" },
  { name = "scala", text = "󰈮" },
  { name = "scm", text = "󰈮" },
  { name = "sh", text = "󰈮" },
  { name = "sig", text = "󰈮" },
  { name = "sml", text = "󰈮" },
  { name = "sql", text = "󰈮" },
  { name = "sv", text = "󰈮" },
  { name = "svh", text = "󰈮" },
  { name = "swift", text = "󰈮" },
  { name = "t", text = "󰈮" },
  { name = "tcl", text = "󰈮" },
  { name = "tf", text = "󰈮" },
  { name = "tmux", text = "󰈮" },
  { name = "ts", text = "󰈮" },
  { name = "tsx", text = "󰈮" },
  { name = "v", text = "󰈮" },
  { name = "vala", text = "󰈮" },
  { name = "vert", text = "󰈮" },
  { name = "vh", text = "󰈮" },
  { name = "vhd", text = "󰈮" },
  { name = "vhdl", text = "󰈮" },
  { name = "vim", text = "󰈮" },
  { name = "vsh", text = "󰈮" },
  { name = "x", text = "󰈮" },
  { name = "xm", text = "󰈮" },
  { name = "xslt", text = "󰈮" },
  { name = "zsh", text = "󰈮" },
]

prepend_conds = [
  # Special files
  { if = "orphan", text = "󰷆", fg = "black" },
  { if = "link", text = "󰬲", fg = "darkgray" },
  { if = "block", text = "󰘓", fg = "yellow" },
  { if = "char", text = "󰘓", fg = "yellow" },
  { if = "fifo", text = "󰘓", fg = "yellow" },
  { if = "sock", text = "󰘓", fg = "yellow" },
  { if = "sticky", text = "", fg = "yellow" },
  { if = "dummy", text = "󰮘", fg = "red" },

  # Fallback
  { if = "dir & hidden", text = "󰉖", fg = "blue" },
  { if = "dir", text = "󰉋", fg = "blue" },
  { if = "exec", text = "󰈮", fg = "green" },
  { if = "!dir & hidden", text = "󰈤", fg = "black" },
  { if = "!dir", text = "󰈔", fg = "black" },
]
